title: <p align="center"> David Aroca </p>

logo: "/images/profile_temp.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/brayan-david-aroca-gonzalez/">LinkedIn</a> |
  <a href="https://github.com/bdarocag">GitHub</a>
  </p>
  
  <p align="justify">
  MS degree in Biostatistics at Manuela Beltrán University.
  <br><br>
  I am currently a Data Scientist at Group COS with a focus on customer segmentation, churn prediction and machine learning algorithms.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-X0YV7KY3YS # Google Analytics tracking ID
