#
###################################
# Site wide configuration
####################################
#
title: bdarocag
email: bdarocag@gmail.com
description: Blog de Brayan David Aroca Gonzalez,powered by jekyll.
url: https://bdarocag.github.io # the base hostname & protocol for your site
keywords: ["jekyll","Biostatistics", "R", "Python","blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Bogota
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-gist
  - jemoji

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: bdarocag
  avatar: avatar.jpg
  job: "Cientifico de datos - Bioestadístico"
  bio: "Científico de datos, apasionado por su trabajo, y los datos biológicos."
  email: bdarocag@gmail.com
  disqus-shortname: #username
  twitter:  @davidgoxo
  facebook: david.gonzalez.xp
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: bdarocag #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
